### ISSUE TITLE
关于2.2.6共振峰的表述

### ISSUE THREAD

**Issue by qq547276542** [cnlinxi/book-text-to-speech#1]
写的非常棒，学到了很多，但其中2.2.6共振峰部分的表述似乎有误。 共振峰是频谱包络的峰，和f0、谐波之间应该是不同概念。 参考 https://www.zhihu.com/question/27126800/answer/35376174

**Comment by cnlinxi** [comment]
> 写的非常棒，学到了很多，但其中2.2.6共振峰部分的表述似乎有误。 共振峰是频谱包络的峰，和f0、谐波之间应该是不同概念。 参考 https://www.zhihu.com/question/27126800/answer/35376174

感谢阅读，迟复为歉。
这里的共振峰表述确实有些问题，已更新该部分表述，感谢勘误。
