### ISSUE TITLE
LJSpeech数据集描述有误

### ISSUE THREAD

**Issue by guoaoo** [cnlinxi/book-text-to-speech#2]
https://github.com/cnlinxi/book-text-to-speech/blob/33021ebf41858b5eaf5b6e8f2b38c5f35c75f34c/text_to_speech.tex#L248
应改为
25小时，采样率22.05kHz

**Comment by cnlinxi** [comment]
> https://github.com/cnlinxi/book-text-to-speech/blob/33021ebf41858b5eaf5b6e8f2b38c5f35c75f34c/text_to_speech.tex#L248
> 
> 
> 应改为
> 25小时，采样率22.05kHz

感谢阅读。
LJSpeech的描述已更新，感谢勘误。
