### ISSUE TITLE
[引用说明]我将您的tex转为markdown并通过github page展示

### ISSUE THREAD

**Issue by makerjackie** [cnlinxi/book-text-to-speech#3]
hi，感谢你写的book-text-to-speech! 非常棒! 对我很有帮助

我在这个[awesome-tts](https://github.com/wespeech/awesome-tts)项目中 复制了你的内容，将 tex 转换为 markdown，[入口在这](https://wespeech.github.io/awesome-tts/)

主要是方便
1. 通过 github page 来展示，
2. 读者可以在文章下方评论（使用了 github discussion）
3. 易于扩展和修改贡献

这个项目现在还在**非常初始**的阶段，

首页中注明了出处，同样采用了 apache 2.0 License

再次感谢

**Comment by cnlinxi** [comment]
> hi，感谢你写的book-text-to-speech! 非常棒! 对我很有帮助
> 
> 我在这个[awesome-tts](https://github.com/we-tts/awesome-tts)项目中 复制了你的内容，将 tex 转换为 markdown，[入口在这](https://we-tts.github.io/awesome-tts/tts-book/%E5%89%8D%E8%A8%80/)
> 
> 主要是方便
> 
> 1. 通过 github page 来展示，
> 2. 读者可以在文章下方评论（使用了 github discussion）
> 3. 易于扩展和修改贡献
> 
> 这个项目现在还在**非常初始**的阶段，
> 
> 首页中注明了出处，同样采用了 apache 2.0 License
> 
> 再次感谢

感谢阅读和使用，期待多多交流
